### ISSUE TITLE
Is it possible to inclue external header files on colab file system?

### ISSUE THREAD

**Issue by asuan99** [andreinechaev/nvcc4jupyter#17]
Is it possible to inclue external header files that are written on external systems like VS ?

Or do I put all headers and source code on colab cells?

If including external header file is possible could you tell me how to use it?

**Comment by andreinechaev** [comment]
Hello there,

The package compiles files within the environment, your file system isn't mapped to the root dir of your notebook it won't be available. The easiest way is to create a cell with that header

**Comment by cosminc98** [comment]
Hello, with the latest release (version 1.1.0) you can now pass any argument to nvcc, such as [--include-path](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#include-path-path-i) which would allow you to include header files from arbitrary directories. [In the documentation](https://nvcc4jupyter.readthedocs.io/en/latest/notebooks.html#compiling-with-external-libraries) you will find a Colab notebook showcasing how to compile and execute CUDA C++ code with an external library (OpenCV). If your problem was not solved, feel free to reopen the issue with more details.
