### ISSUE TITLE
cuda_runtime.h error on kaggle

### ISSUE THREAD

**Issue by mmmovania** [andreinechaev/nvcc4jupyter#29]
I am trying to run a basic CUDA code on kaggle. 
```
%%cuda
#include <stdio.h>
​
__global__ void HelloKernel() {
    printf("\tHello from GPU (device)\n");
}
​
int main() {
  printf("Hello from CPU (host) before kernel execution\n");
  HelloKernel<<<1,32>>>();
  cudaDeviceSynchronize();
  printf("Hello from CPU (host) after kernel execution\n");
  return 0;
}
```
The same code works fine on Colab but on Kaggle it gives this error.
```
cc1plus: fatal error: cuda_runtime.h: No such file or directory
compilation terminated.
```
Any idea on what might be causing this?

**Comment by cosminc98** [comment]
Hello @mmmovania,

According to [this post](https://forums.developer.nvidia.com/t/cc1plus-fatal-error-cuda-runtime-h-no-such-file-or-directory-compilation-terminated/79998) from the nvidia forum, it looks like a broken CUDA install. I will test it as soon as I have time to see if there is a solution for it.

**Comment by cosminc98** [comment]
The problem seems to be that the "nvidia-cuda-toolkit" package is not installed. After this, it seems that another error appears that is related to a wrong version of gcc. You can fix it by adding a new directory to the PATH environment variable (at the beginning so it is prioritized) where you put a symbolic link to the correct gcc version that is already installed in kaggle.

Cell 1:
```bash
!apt install -y nvidia-cuda-toolkit; mkdir /usr/bin/priority; ln -s /usr/bin/gcc-8 /usr/bin/priority/gcc
```

Cell 2:
```bash
import os
os.environ["PATH"] = "/usr/bin/priority:" + os.environ["PATH"]
```

If this does not solve your problem feel free to reopen the issue.

**Comment by mmmovania** [comment]
Yep that was it. It works :)

**Comment by cosminc98** [comment]
The extension now runs these steps for you when it is loaded.
